// ~~~~~~~~~~~~~~~ POKEMON GAMES ~~~~~~~~~~~~~~~
/*
  ~~~~~ RULES ~~~~~
  [1] BRACKETING OF MATCHES (WINNER & LOSER)
  [2] TOP 3 - ROUND ROBIN
  [3] FAINTED POKEMONS WILL BE REVIVED IN 2ND BRACKET
  [4] PROMP TRAINERS & POKEMONS
*/
